### ISSUE TITLE
[Principles Section 4] proofread Embodied Carbon including graphics for summit's deck

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/green-software-principles#42]
[Embodied Carbon](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/embodied-carbon.md)

**Comment by greenhsu123** [comment]
For this sub-section -[extending-the-lifespan-of-hardware](https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/Principles/embodied-carbon.md#extending-the-lifespan-of-hardware),let's use what the [graphics ](https://principles.green/principles/embodied-carbon/#heading-extending-the-lifespan-of-hardware) from version 1

**Comment by SravanthiAshokKumar** [comment]
#1. "We can do many things to be hardware efficient, but one thing ....." -> Would it be better to list down more ways to be hardware efficient in this section than just mentioning there are many ways? 
- Can reusing hardware can be stated as one of the ways to be hardware-efficient? ie. in case there's one part of a processor that stops working, it is enough to just replace just that part rather than replacing the entire processor. 
- Another point can be that, it is also important to manufacture hardware such that it can be backward compatible ie. a hardware piece inside a new processor should be able to work with a previous version of the processor so as to be able to do the above mentioned reuse.


2. "Computers don't wear out; there are no moving parts; they just become obsolete." -> Agreed that they get outdated but, computers not having moving parts or not wearing out might not be exactly true. For example, in a HDD, there are a set of spinning disks and there's a head that moves to read and write data. So these disks are in high stress while they are working, which can eventually cause them to wear out. Similarly the processor has a bunch of moving parts which can also wear out eventually.

3. "Hardware is retired either because it breaks down or because ... Software cannot help with the first ...." -> Here, does "breaks down" refers to random hardware failure (like manufacturing defect - which we cannot help) or  failure due to wear and tear? "Software cannot help with the first" might not be the case always. Because, hardware's lifespan can be extended with efficient software. For example, consider the example of an HDD where it can wear out faster with more reads/writes to it. If software is written in such a way that the reads/writes are not optimized, it leads to more work to the disks leading to faster wear & tear. In other words, if there's a possibility that the same result can be achieved with lesser reads/writes, then the hardware can last longer.

**Comment by greenhsu123** [comment]
Completed!
